---
# tasks file for ansible-role-common

- include: debian.yml
  when:
    ansible_os_family == "Debian"

- include: rhel.yml
  when:
    ansible_os_family == "RedHat"

- name: Install common packages (any os)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ common_packages }}"
